name: Docker Build and Push Compressors

on:
  push:
    branches: [ main ] # Assuming master is the main branch, adjust if needed

jobs:
  build-and-push-js_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push JS Compressor
        uses: docker/build-push-action@v5
        with:
          context: ./js-compressor
          file: ./js-compressor/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/nkwenti-severian-ndongtsop/compress-js:latest

  build-and-push-rs_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Rust Compressor
        uses: docker/build-push-action@v5
        with:
          context: ./rust-compressor
          file: ./rust-compressor/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/nkwenti-severian-ndongtsop/compress-rs:latest 